version: '3'
services:
  misc:
    image: 172232502/misc
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - './.env:/app/.env'
      - './plusPosts:/app/plusPosts'
      - 'ashare-data:/app/deliverables'
    ports:
      - 3010:3010

  ashare-signal:
    image: 172232502/ashare-signal
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    env_file:
      - ./.env
    volumes:
      - 'ashare-data:/app/deliverables'
      - './monitor/feishu_webhook.json:/app/monitor/feishu_webhook.json:ro'

volumes:
  ashare-data:
