version: '3'
services:
  misc:
    image: 172232502/misc
    #build:
    #  context: .
    #    dockerfile: ./Dockerfile
    restart: always
    volumes:
      - './.env:/app/.env'
      - './prisma/dev.db:/app/prisma/dev.db'
      - './plusPosts:/app/plusPosts'
    #   - ./json:/usr/share/nginx/html/json
    ports:
      - 3010:3010
        #- 3000:3000
    # network_mode: 'host'
