version: '3'
services:
  misc:
    image: 172232502/misc-2
    #build:
    #  context: .
    #    dockerfile: ./Dockerfile
    restart: always
    volumes:
      - './.env.local:/app/.env.local'
      # - './access.log:/app/access.log'
    #   - ./json:/usr/share/nginx/html/json
    ports:
      - 3010:3010
    # network_mode: 'host'
