name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: zqcccc/docker-image-version@0.2
      id: version
      with:
        repository: 172232502/misc
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Build the Docker image
    #   run: docker buildx create --use --driver-opt network=host && docker buildx build --platform=linux/amd64,linux/arm64 -t 172232502/misc -t 172232502/misc:${{ steps.version.outputs.next_version }} . --push
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - 
      name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ｜
          172232502/misc:latest
          172232502/misc:${{ steps.version.outputs.next_version }}
        labels: 172232502/misc:${{ steps.version.outputs.next_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
